version: '3.6'

services:
  flame:
    image: pawelmalak/flame:multiarch2.3.0
    volumes:
      - /homelab/flame/flame-data:/app/data
      - /var/run/docker.sock:/var/run/docker.sock # optional but required for Docker integration
    networks:
      default:
      traefik:
    secrets:
      - password # optional but required for (1)
    environment:
      - PASSWORD_FILE=/run/secrets/password # optional but required for (1)
    restart: unless-stopped
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.flame.rule=Host(`papatohu.p2.network`)'
      - 'traefik.http.routers.flame.entrypoints=web'
      - "traefik.http.routers.flame.middlewares=cf-connecting-ip@file,flame-auth@docker"
      - "traefik.http.middlewares.flame-auth.forwardauth.address=http://traefik-auth-cloudflare:8080/auth/1737aed47ce6e20a640280f497bf8885211f78db12f6231bbd76e8bf99f5ab3a"
      - "traefik.http.middlewares.flame-auth.forwardauth.authResponseHeaders=X-Auth-User"

secrets:
  password:
    file: /opt/p2-network/run/DOCKER_FLAME_PASSWORD

networks:
  traefik:
    name: traefik_default
    external: true

volumes:
