version: "3.3"

services:
  traefik:
    image: "traefik:2.10.5"
    restart: unless-stopped
    container_name: "traefik"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`snappy-traefik.p2.network`)"
      - "traefik.http.routers.api.entrypoints=web"
      - "traefik.http.routers.api.service=api@internal"
      - "traefik.http.routers.api.middlewares=cf-connecting-ip@file,api-auth@docker"
      - "traefik.http.middlewares.api-auth.forwardauth.address=http://traefik-auth-cloudflare:8080/auth/490dc06b90c4f76e091e6a48ef0e168d78c19a032e3ab7783236cad7f8be844d"
      - "traefik.http.middlewares.api-auth.forwardauth.authResponseHeaders=X-Auth-User"
    command:
      #- "--log.level=DEBUG"
      - "--api"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entryPoints.web.forwardedHeaders.trustedIPs=172.19.0.0/16"
      - "--entrypoints.websecure.address=:443"
      - "--entryPoints.websecure.forwardedHeaders.trustedIPs=172.19.0.0/16"

      - "--certificatesresolvers.p2.acme.storage=/etc/traefik-acme/acme.json"
      - "--certificatesresolvers.p2.acme.dnschallenge.provider=cloudflare"
      - "--certificatesresolvers.p2.acme.dnschallenge.delaybeforecheck=0"

      - "--certificatesresolvers.campjs.acme.storage=/etc/traefik-acme/campjs.json"
      - "--certificatesresolvers.campjs.acme.tlschallenge=true"

      - "--certificatesresolvers.route53.acme.storage=/etc/traefik-acme/route53.json"
      - "--certificatesresolvers.route53.acme.dnschallenge.provider=route53"
      - "--certificatesresolvers.route53.acme.dnschallenge.delaybeforecheck=0"

      - "--experimental.plugins.real-ip.moduleName=github.com/Paxxs/traefik-get-real-ip"
      - "--experimental.plugins.real-ip.version=v1.0.2"
      - "--providers.file.directory=/etc/traefik/"
      - "--providers.file.watch=true"
      - "--providers.docker.network=traefik_default"
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      - target: 443
        published: 443
        protocol: tcp
        mode: host
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - ./traefik/:/etc/traefik/
      - "/opt/p2-network/traefik-acme/:/etc/traefik-acme/"
    environment:
      - TZ=Australia/Melbourne
      - CLOUDFLARE_DNS_API_TOKEN_FILE=/run/secrets/cf_dns_api_token
      - AWS_ACCESS_KEY_ID_FILE=/run/secrets/route53_access_key
      - AWS_SECRET_ACCESS_KEY_FILE=/run/secrets/route53_access_secret
      - AWS_REGION=ap-southeast-2
      - TRAEFIK_CERTIFICATESRESOLVERS_p2_ACME_EMAIL_FILE=/run/secrets/acme_email
      - TRAEFIK_CERTIFICATESRESOLVERS_campjs_ACME_EMAIL_FILE=/run/secrets/acme_email
    secrets:
      - cf_dns_api_token
      - route53_access_key
      - route53_access_secret
      - acme_email

  traefik-auth-cloudflare:
    image: akohlbecker/traefik-auth-cloudflare
    restart: always
    expose:
      - 8080
    container_name: traefik-auth-cloudflare
    command: ["--auth-domain", "https://patrick.cloudflareaccess.com"]

  echo:
    image: traefik/whoami:v1.10.1
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami-secure.rule=Host(`echo.p2.network`)"
      - "traefik.http.routers.whoami-secure.entrypoints=web"
      - "traefik.http.routers.whoami-secure.middlewares=cf-connecting-ip@file,echo-auth@docker"
      # Each request is first forwarded to traefik-auth-cloudflare to check the JWT token
      # the Application Audience (aud) tag is given as an URL parameter: `/auth/{audience}`
      - "traefik.http.middlewares.echo-auth.forwardauth.address=http://traefik-auth-cloudflare:8080/auth/c5d123c90cba3d592e8e76f3ec5be4cd2da68bb733abb35cf296e855605310a9"
      # Optional: Forward the X-Auth-User header to the backend, which is set by traefik-auth-cloudflare to contain the user email
      - "traefik.http.middlewares.echo-auth.forwardauth.authResponseHeaders=X-Auth-User"

secrets:
  route53_access_key:
    file: /opt/p2-network/run/DOCKER_TRAEFIK_ROUTE53_ACCESSKEY
  route53_access_secret:
    file: /opt/p2-network/run/DOCKER_TRAEFIK_ROUTE53_SECRET
  cf_dns_api_token:
    file: /opt/p2-network/run/DOCKER_TRAEFIK_CF_DNS_API_TOKEN
  acme_email:
    file: /opt/p2-network/run/DOCKER_TRAEFIK_ACME_EMAIL
