version: "3.3"

services:
  traefik:
    image: "traefik:v2.11.4"
    restart: unless-stopped
    container_name: "traefik"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api-tailscale.rule=Host(`traefik.snappy.thepatrick.cloud`) && ClientIP(`100.0.0.0/8`, `fd7a:115c:a1e0:ab12::/64`)"
      - "traefik.http.routers.api-tailscale.entrypoints=websecure"
      - "traefik.http.routers.api-tailscale.service=api@internal"
      - "traefik.http.routers.api-tailscale.tls=true"
      - "traefik.http.routers.api-tailscale.tls.certresolver=route53"
      - "traefik.http.routers.api-tailscale.tls.domains[0].main=*.snappy.thepatrick.cloud"
      # - "traefik.http.routers.api-tailscale.middlewares=oauth2-proxy-redirect@docker"
    command:
      #- "--log.level=DEBUG"
      - "--api"

      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=traefik_default"

      - "--providers.file.directory=/etc/traefik/"
      - "--providers.file.watch=true"

      - "--entrypoints.web.address=:80"
      - "--entryPoints.web.forwardedHeaders.trustedIPs=172.19.0.0/16"
      - "--entrypoints.websecure.address=:443"
      - "--entryPoints.websecure.forwardedHeaders.trustedIPs=172.19.0.0/16"

      - "--certificatesresolvers.campjs.acme.storage=/etc/traefik-acme/campjs.json"
      - "--certificatesresolvers.campjs.acme.tlschallenge=true"

      - "--certificatesresolvers.route53.acme.storage=/etc/traefik-acme/route53.json"
      - "--certificatesresolvers.route53.acme.dnschallenge.provider=route53"
      - "--certificatesresolvers.route53.acme.dnschallenge.delaybeforecheck=0"

      - "--experimental.plugins.real-ip.moduleName=github.com/Paxxs/traefik-get-real-ip"
      - "--experimental.plugins.real-ip.version=v1.0.2"
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      - target: 443
        published: 443
        protocol: tcp
        mode: host
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - ./traefik/:/etc/traefik/
      - "/opt/p2-network/traefik-acme/:/etc/traefik-acme/"
      - "/opt/p2-network/run/DOCKER_TRAEFIK_AWS_SHARED_CREDENTIALS_FILE:/etc/traefik-aws-credentials"
    environment:
      - TZ=Australia/Melbourne
      - AWS_SHARED_CREDENTIALS_FILE=/etc/traefik-aws-credentials
      - AWS_REGION=ap-southeast-2
      - TRAEFIK_CERTIFICATESRESOLVERS_p2_ACME_EMAIL_FILE=/run/secrets/acme_email
      - TRAEFIK_CERTIFICATESRESOLVERS_campjs_ACME_EMAIL_FILE=/run/secrets/acme_email
    secrets:
      - acme_email

secrets:
  acme_email:
    file: /opt/p2-network/run/DOCKER_TRAEFIK_ACME_EMAIL
