http:
  routers:
    portainer-api:
      rule: "Host(`portainer.i.m.ac.nz`) && PathPrefix(`/api/stacks/webhooks`)"
      service: portainer
      entrypoints: websecure
      tls:
        certResolver: route53
        domains:
        - main: "*.i.m.ac.nz"

    portainer-ui:
      rule: "Host(`portainer.i.m.ac.nz`)"
      service: portainer
      entrypoints: websecure
      tls:
        certResolver: route53
        domains:
        - main: "*.i.m.ac.nz"
      middlewares:
      - oauth2-proxy-headers@docker

  services:
    portainer:
      loadBalancer:
        servers:
        - url: "https://100.102.143.73:9443"
