http:
  routers:
    portainer-api:
      rule: "Host(`portainer.i.m.ac.nz`) && PathPrefix(`/api/stacks/webhooks`)"
      service: portainer
      entrypoints: websecure
      tls:
        certResolver: route53
        domains:
        - main: "*.i.m.ac.nz"

    portainer-ui:
      rule: "Host(`portainer.i.m.ac.nz`)"
      service: portainer
      entrypoints: websecure
      tls:
        certResolver: route53
        domains:
        - main: "*.i.m.ac.nz"
      middlewares:
      - oauth2-proxy-headers@docker

    portainer-ui-ts:
      rule: "Host(`portainer.snappy.thepatrick.cloud`) && ClientIP(`100.0.0.0/8`, `fd7a:115c:a1e0:ab12::/64`)"
      service: portainer
      entrypoints: websecure
      tls:
        certResolver: route53
        domains:
        - main: "*.snappy.thepatrick.cloud"

  services:
    portainer:
      loadBalancer:
        servers:
        - url: "https://172.17.0.1:9443"
